# Site settings
title: Samuel Merren
description: >-
  He's writing in Bahasa about web technology and experience as a journal 
  for documentation things that he learned, meet him <a href="https://github.com/piharpi" target="_blank" rel="noopener">@github</a>.
lang: en-US
timezone: Australia/Hobart
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/piharpi/mahendrata.now.sh
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Samuel Merren
  bio: >-
    Welcome! My name is Sam Merren, i'm a C/C++/Java/Python developer and Software
    Security enthusiast from Melbourne, currently studying Computer Science at Monash University. 
    This Website contains everything I have been working on since 2020, a blog for anything 
    interesting I might want to write about (mainly CTF writeups), and any project showcases i'd
    like to display. <a href="https://github.com/CasparovJR" target="_blank" rel="noopener">@github</a>.
  username: username
  email: your-email@email.com
  avatar: /assets/img/avatar.jpg

# Url settings
url: ""
baseurl:""
permalink: /:title/
google_analytics:
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Build settings
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sass-converter
  - jekyll-sitemap
  - jekyll-postfiles
